### ISSUE TITLE
ODBExtract - issue when with same name jar file overwriting

### ISSUE THREAD

**Issue by WSorban** [jglim/ODB#2]
Sometimes the jar file can have the same name, then it gets overwritten.
Changing this line of code, in Program.cs, to the following, should fix the problem:
`File.WriteAllBytes($"{Path.GetFileNameWithoutExtension(fileName)}_{i}_{preferredName}", extractedZips[i]);`

**Comment by jglim** [comment]
Fixed, thanks for pointing that out!
