### ISSUE TITLE
Release binary

### ISSUE THREAD

**Issue by Flo354** [jglim/ODB#3]
Hello there,

Sometimes I am using your tool, but I am not always on a machine that can compiles your the program.
Would it be possible for you to release an executable so we can use it without installing the tools to compile it?

Thank you,

**Comment by jglim** [comment]
Hello Flo354,

I've added a Github Action to build the project and upload the output artifacts. These artifacts will eventually expire, but should work well enough for the use case here.

The latest nightly download link is [available here](https://nightly.link/jglim/ODB/workflows/dotnet-desktop/main/ODBExtract%20%28Windows%2C%20ZIP%29.zip).

**Comment by Flo354** [comment]
Thank you!
