### ISSUE TITLE
contact you re mistake on ppdcl website 

### ISSUE THREAD

**Issue by Ok45sg** [jglim/ODB#4]
Hi, I don't know how to get to your email address. So I use this page. 
Thanks for freely creating the website ppcdl.sn.sg to benefit fellow test takers. I failed once. Ha ha. Like to point out the error on 1st set of questions, Q 21.
When proceeding west, if you see a east cardinal buoy, you should : 
the correct answer that is correct is: u-turn and go back. It should be "alter course 45 degrees to port or starboard and proceed till the buoy is due north or south. "
Thanks for your generosity. kim ong. 
 ok45sg@gmail.com 
Somehow I can't get twitter to work.

**Comment by jglim** [comment]
Hi Kim,

Thanks for your kind words and for taking time to correct my mistake! I have applied the fix immediately. 
I'll also email you a copy of this comment and remove this issue.

Have a good holiday!
